alphafold3:
  model_dir: /cluster/project/beltrao/lucla/alphafold_models
  max_template_date: '2099-01-01'
  data_sources: >-
    --data_dir=./alphafold3_msas
  predictions:
    slurm_extra: '--gpus=1'
    high_vram_slurm_extra: '--gpus=rtx_3090:1'
    token_threshold: 500
    retries: 2
    mem_mb: 16384
    singularity_args: '--env XLA_FLAGS="--xla_disable_hlo_passes=custom-kernel-fusion-rewriter"'
    run_alphafold_args: >-
      --num_recycles=3
      --max_template_date=2099-01-01
      --flash_attention_implementation=xla
      --model_dir=/root/models/af3.bin.zst

gnina:
  mode: "redock"  # Options: "score_only", "minimize", "redock"
  autobox_add: 8.0  # Box size expansion in Angstroms around AF3 ligand for redocking/minimization
